<a href="https://colab.research.google.com/github/hussainiram0601-lang/KerasTuner-DNN-Optimized/blob/main/KerasTuner_DNN_Optimized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv('/content/diabetes.csv')

In [39]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [40]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [41]:
X = df.iloc[:,:-1].values

In [42]:
y = df.iloc[:,-1].values

In [43]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X = sc.fit_transform(X)

In [44]:
from sklearn.model_selection import train_test_split
X_train  , X_test, y_train , y_test = train_test_split(X, y , test_size = 0.2 , random_state=42)

In [55]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [46]:
from keras.src.metrics.accuracy_metrics import accuracy
model = Sequential()
model.add(Dense(32 , activation='relu' , input_dim = 8))
model.add(Dense(16 , activation ='relu'))
model.add(Dense(1 , activation='sigmoid'))

model.compile(optimizer = 'Adam' , loss = 'binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [47]:
model.fit(X_train, y_train, batch_size = 32, epochs = 100 , validation_data=(X_test, y_test) )

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.6645 - loss: 0.6491 - val_accuracy: 0.6818 - val_loss: 0.6484
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7427 - loss: 0.5752 - val_accuracy: 0.6948 - val_loss: 0.6184
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7508 - loss: 0.5418 - val_accuracy: 0.7013 - val_loss: 0.6022
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5168 - val_accuracy: 0.7143 - val_loss: 0.5899
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7541 - loss: 0.4988 - val_accuracy: 0.7208 - val_loss: 0.5790
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.4871 - val_accuracy: 0.7208 - val_loss: 0.5747
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4766 - val_accuracy: 0.7273 - val_loss: 0.5692
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7687 - loss: 0.4695 - val_accuracy: 0.7208 - val_loss: 0.5652
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.4633 - val_accuracy: 0.7403 - val_loss: 0.5634
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4582 - val_accuracy: 0.7338 - val_loss: 0.5627
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4530 - val_accuracy: 0.7403 - val_loss: 0.5622
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4500 - val_accuracy: 0.7338 - val_loss: 0.5614
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4453 - val_accuracy: 0.7532 - val_loss: 0.5592
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4415 - val_accuracy: 0.7468 - val_loss: 0.5593
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4387 - val_accuracy: 0.7532 - val_loss: 0.5567
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4359 - val_accuracy: 0.7532 - val_loss: 0.5581
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4329 - val_accuracy: 0.7597 - val_loss: 0.5612
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4307 - val_accuracy: 0.7727 - val_loss: 0.5619
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4281 - val_accuracy: 0.7662 - val_loss: 0.5633
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4268 - val_accuracy: 0.7468 - val_loss: 0.5650
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4272 - val_accuracy: 0.7662 - val_loss: 0.5725
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4228 - val_accuracy: 0.7403 - val_loss: 0.5721
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4202 - val_accuracy: 0.7468 - val_loss: 0.5740
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4195 - val_accuracy: 0.7597 - val_loss: 0.5777
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4166 - val_accuracy: 0.7597 - val_loss: 0.5783
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4152 - val_accuracy: 0.7597 - val_loss: 0.5798
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4132 - val_accuracy: 0.7662 - val_loss: 0.5802
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4127 - val_accuracy: 0.7662 - val_loss: 0.5834
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4099 - val_accuracy: 0.7597 - val_loss: 0.5849
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4094 - val_accuracy: 0.7662 - val_loss: 0.5834
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4085 - val_accuracy: 0.7662 - val_loss: 0.5793
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4067 - val_accuracy: 0.7662 - val_loss: 0.5783
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4049 - val_accuracy: 0.7597 - val_loss: 0.5776
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4039 - val_accuracy: 0.7662 - val_loss: 0.5829
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4022 - val_accuracy: 0.7662 - val_loss: 0.5812
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4015 - val_accuracy: 0.7662 - val_loss: 0.5808
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4008 - val_accuracy: 0.7727 - val_loss: 0.5832
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3982 - val_accuracy: 0.7727 - val_loss: 0.5819
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3978 - val_accuracy: 0.7662 - val_loss: 0.5838
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3979 - val_accuracy: 0.7597 - val_loss: 0.5897
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5863
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3940 - val_accuracy: 0.7597 - val_loss: 0.5895
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3926 - val_accuracy: 0.7532 - val_loss: 0.5883
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3919 - val_accuracy: 0.7532 - val_loss: 0.5911
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8225 - loss: 0.3917 - val_accuracy: 0.7597 - val_loss: 0.5884
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3893 - val_accuracy: 0.7662 - val_loss: 0.5907
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3897 - val_accuracy: 0.7597 - val_loss: 0.5965
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3869 - val_accuracy: 0.7727 - val_loss: 0.5946
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3876 - val_accuracy: 0.7662 - val_loss: 0.5935
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3861 - val_accuracy: 0.7662 - val_loss: 0.5965
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3839 - val_accuracy: 0.7532 - val_loss: 0.5976
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3824 - val_accuracy: 0.7662 - val_loss: 0.5935
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3840 - val_accuracy: 0.7662 - val_loss: 0.5871
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3828 - val_accuracy: 0.7662 - val_loss: 0.5921
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3814 - val_accuracy: 0.7597 - val_loss: 0.5928
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3795 - val_accuracy: 0.7532 - val_loss: 0.5903
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3803 - val_accuracy: 0.7662 - val_loss: 0.5893
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3787 - val_accuracy: 0.7597 - val_loss: 0.5904
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3764 - val_accuracy: 0.7597 - val_loss: 0.5887
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3760 - val_accuracy: 0.7662 - val_loss: 0.5949
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3742 - val_accuracy: 0.7532 - val_loss: 0.5949
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3731 - val_accuracy: 0.7403 - val_loss: 0.6006
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3733 - val_accuracy: 0.7597 - val_loss: 0.6004
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3713 - val_accuracy: 0.7532 - val_loss: 0.5950
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3705 - val_accuracy: 0.7597 - val_loss: 0.5971
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3688 - val_accuracy: 0.7468 - val_loss: 0.5972
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3689 - val_accuracy: 0.7532 - val_loss: 0.5950
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3684 - val_accuracy: 0.7597 - val_loss: 0.5997
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3672 - val_accuracy: 0.7597 - val_loss: 0.6004
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3657 - val_accuracy: 0.7403 - val_loss: 0.6036
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3649 - val_accuracy: 0.7403 - val_loss: 0.6014
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3640 - val_accuracy: 0.7532 - val_loss: 0.6019
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3638 - val_accuracy: 0.7468 - val_loss: 0.6026
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3637 - val_accuracy: 0.7597 - val_loss: 0.6010
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3616 - val_accuracy: 0.7468 - val_loss: 0.6052
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3624 - val_accuracy: 0.7662 - val_loss: 0.6025
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3599 - val_accuracy: 0.7597 - val_loss: 0.6070
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3587 - val_accuracy: 0.7532 - val_loss: 0.6071
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3576 - val_accuracy: 0.7597 - val_loss: 0.6069
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3583 - val_accuracy: 0.7403 - val_loss: 0.6118
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8388 - loss: 0.3571 - val_accuracy: 0.7468 - val_loss: 0.6060
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8436 - loss: 0.3565 - val_accuracy: 0.7468 - val_loss: 0.6062
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8436 - loss: 0.3550 - val_accuracy: 0.7468 - val_loss: 0.6087
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8453 - loss: 0.3528 - val_accuracy: 0.7403 - val_loss: 0.6120
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8550 - loss: 0.3535 - val_accuracy: 0.7468 - val_loss: 0.6103
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3520 - val_accuracy: 0.7468 - val_loss: 0.6140
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8453 - loss: 0.3518 - val_accuracy: 0.7468 - val_loss: 0.6134
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8469 - loss: 0.3518 - val_accuracy: 0.7532 - val_loss: 0.6145
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3503 - val_accuracy: 0.7403 - val_loss: 0.6208
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8518 - loss: 0.3481 - val_accuracy: 0.7468 - val_loss: 0.6215
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3476 - val_accuracy: 0.7532 - val_loss: 0.6119
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3457 - val_accuracy: 0.7468 - val_loss: 0.6148
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3469 - val_accuracy: 0.7468 - val_loss: 0.6151
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3462 - val_accuracy: 0.7532 - val_loss: 0.6149
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3450 - val_accuracy: 0.7532 - val_loss: 0.6170
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3441 - val_accuracy: 0.7468 - val_loss: 0.6153
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3421 - val_accuracy: 0.7597 - val_loss: 0.6155
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3406 - val_accuracy: 0.7532 - val_loss: 0.6201
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3406 - val_accuracy: 0.7468 - val_loss: 0.6221
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3404 - val_accuracy: 0.7468 - val_loss: 0.6225

In [48]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.13/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.84.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (6.33.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [49]:
import kerastuner as kt

In [61]:
from keras.src.optimizers import adadelta
def build_model(hp):
  model = Sequential()
  cnt = 0
  for i in range(hp.Int('num_layers', min_value=1 , max_value = 10)):
    if cnt == 0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value = 128),
                      activation= hp.Choice('activation'+str(i),values=['relu','sigmoid','tanh','softmax']),
                      input_dim=8))
      model.add(Dropout(hp.Choice('dropout'+str(i),values =[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value = 128),
                      activation= hp.Choice('activation'+str(i),values=['relu','sigmoid','tanh','softmax']),
                      ))
      model.add(Dropout(hp.Choice('dropout'+str(i),values =[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    cnt+=1
  model.add(Dense(1, activation= 'sigmoid'))
  model.compile(optimizer = hp.Choice('optimizer',values=['adam','adagrad','adadelta','rmsprop','sgd','nadam']),
                loss = 'binary_crossentropy',
                metrics = ['accuracy'])
  return model

In [66]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy',max_trials=3,directory='mydir',project_name = 'Final2')
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 06s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6688311696052551
Total elapsed time: 00h 00m 16s

In [63]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 60,
 'activation0': 'relu',
 'optimizer': 'rmsprop',
 'units1': 50,
 'activation1': 'sigmoid',
 'units2': 43,
 'activation2': 'tanh',
 'units3': 73,
 'activation3': 'sigmoid',
 'units4': 49,
 'activation4': 'relu',
 'units5': 57,
 'activation5': 'tanh',
 'units6': 12,
 'activation6': 'sigmoid',
 'units7': 86,
 'activation7': 'sigmoid',
 'units8': 37,
 'activation8': 'tanh'}

In [67]:
model = tuner.get_best_models(num_models=1)[0]

In [69]:
model.fit(X_train, y_train, epochs= 200 , initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7345 - loss: 0.5548 - val_accuracy: 0.7792 - val_loss: 0.5307
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7492 - loss: 0.5253 - val_accuracy: 0.7727 - val_loss: 0.5301
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7182 - loss: 0.5482 - val_accuracy: 0.7792 - val_loss: 0.5288
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5579 - val_accuracy: 0.7662 - val_loss: 0.5338
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5361 - val_accuracy: 0.7792 - val_loss: 0.5293
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5207 - val_accuracy: 0.7792 - val_loss: 0.5284
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5342 - val_accuracy: 0.7792 - val_loss: 0.5278
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7443 - loss: 0.5153 - val_accuracy: 0.7792 - val_loss: 0.5254
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5504 - val_accuracy: 0.7792 - val_loss: 0.5277
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5261 - val_accuracy: 0.7792 - val_loss: 0.5272
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5266 - val_accuracy: 0.7792 - val_loss: 0.5264
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5490 - val_accuracy: 0.7792 - val_loss: 0.5265
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5125 - val_accuracy: 0.7857 - val_loss: 0.5265
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5166 - val_accuracy: 0.7857 - val_loss: 0.5227
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5345 - val_accuracy: 0.7792 - val_loss: 0.5236
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5450 - val_accuracy: 0.7922 - val_loss: 0.5245
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5314 - val_accuracy: 0.7922 - val_loss: 0.5237
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5319 - val_accuracy: 0.7857 - val_loss: 0.5246
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5498 - val_accuracy: 0.7857 - val_loss: 0.5241
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5354 - val_accuracy: 0.7857 - val_loss: 0.5260
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5251 - val_accuracy: 0.7857 - val_loss: 0.5239
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5294 - val_accuracy: 0.7857 - val_loss: 0.5240
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5257 - val_accuracy: 0.7857 - val_loss: 0.5267
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5073 - val_accuracy: 0.7857 - val_loss: 0.5249
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5176 - val_accuracy: 0.7792 - val_loss: 0.5271
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5336 - val_accuracy: 0.7792 - val_loss: 0.5268
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7280 - loss: 0.5328 - val_accuracy: 0.7857 - val_loss: 0.5245
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5069 - val_accuracy: 0.7727 - val_loss: 0.5250
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5238 - val_accuracy: 0.7857 - val_loss: 0.5243
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4933 - val_accuracy: 0.7792 - val_loss: 0.5232
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7443 - loss: 0.5196 - val_accuracy: 0.7857 - val_loss: 0.5222
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7378 - loss: 0.5337 - val_accuracy: 0.7857 - val_loss: 0.5217
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7606 - loss: 0.5141 - val_accuracy: 0.7857 - val_loss: 0.5215
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7329 - loss: 0.5244 - val_accuracy: 0.7922 - val_loss: 0.5214
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5146 - val_accuracy: 0.7922 - val_loss: 0.5211
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5284 - val_accuracy: 0.7857 - val_loss: 0.5207
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7313 - loss: 0.5361 - val_accuracy: 0.7857 - val_loss: 0.5211
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7638 - loss: 0.5006 - val_accuracy: 0.7792 - val_loss: 0.5208
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.5065 - val_accuracy: 0.7857 - val_loss: 0.5209
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5170 - val_accuracy: 0.7857 - val_loss: 0.5203
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5111 - val_accuracy: 0.7857 - val_loss: 0.5216
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5255 - val_accuracy: 0.7857 - val_loss: 0.5217
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5272 - val_accuracy: 0.7857 - val_loss: 0.5206
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5270 - val_accuracy: 0.7922 - val_loss: 0.5195
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5072 - val_accuracy: 0.7922 - val_loss: 0.5195
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5135 - val_accuracy: 0.7857 - val_loss: 0.5194
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5097 - val_accuracy: 0.7922 - val_loss: 0.5212
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4950 - val_accuracy: 0.7857 - val_loss: 0.5205
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5186 - val_accuracy: 0.7922 - val_loss: 0.5202
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5155 - val_accuracy: 0.7857 - val_loss: 0.5201
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5087 - val_accuracy: 0.7857 - val_loss: 0.5191
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5116 - val_accuracy: 0.7857 - val_loss: 0.5191
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4997 - val_accuracy: 0.7792 - val_loss: 0.5180
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5035 - val_accuracy: 0.7792 - val_loss: 0.5185
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5061 - val_accuracy: 0.7468 - val_loss: 0.5186
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5129 - val_accuracy: 0.7922 - val_loss: 0.5216
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5218 - val_accuracy: 0.7922 - val_loss: 0.5228
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5079 - val_accuracy: 0.7792 - val_loss: 0.5241
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5045 - val_accuracy: 0.7857 - val_loss: 0.5233
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5059 - val_accuracy: 0.7792 - val_loss: 0.5236
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5111 - val_accuracy: 0.7727 - val_loss: 0.5241
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4940 - val_accuracy: 0.7727 - val_loss: 0.5243
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5068 - val_accuracy: 0.7727 - val_loss: 0.5242
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4851 - val_accuracy: 0.7662 - val_loss: 0.5241
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4881 - val_accuracy: 0.7662 - val_loss: 0.5250
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4901 - val_accuracy: 0.7662 - val_loss: 0.5252
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4993 - val_accuracy: 0.7662 - val_loss: 0.5255
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7248 - loss: 0.5031 - val_accuracy: 0.7532 - val_loss: 0.5257
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4936 - val_accuracy: 0.7532 - val_loss: 0.5254
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5025 - val_accuracy: 0.7597 - val_loss: 0.5240
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4965 - val_accuracy: 0.7597 - val_loss: 0.5231
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5147 - val_accuracy: 0.7597 - val_loss: 0.5235
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4953 - val_accuracy: 0.7597 - val_loss: 0.5236
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4706 - val_accuracy: 0.7597 - val_loss: 0.5241
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5099 - val_accuracy: 0.7597 - val_loss: 0.5242
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.4933 - val_accuracy: 0.7532 - val_loss: 0.5250
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5219 - val_accuracy: 0.7857 - val_loss: 0.5234
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5114 - val_accuracy: 0.7922 - val_loss: 0.5254
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4819 - val_accuracy: 0.7857 - val_loss: 0.5250
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5193 - val_accuracy: 0.7857 - val_loss: 0.5244
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5027 - val_accuracy: 0.7662 - val_loss: 0.5270
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5071 - val_accuracy: 0.7662 - val_loss: 0.5276
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5057 - val_accuracy: 0.7662 - val_loss: 0.5269
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5003 - val_accuracy: 0.7662 - val_loss: 0.5273
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5032 - val_accuracy: 0.7597 - val_loss: 0.5277
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4862 - val_accuracy: 0.7597 - val_loss: 0.5273
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5036 - val_accuracy: 0.7597 - val_loss: 0.5271
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4877 - val_accuracy: 0.7597 - val_loss: 0.5259
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4996 - val_accuracy: 0.7597 - val_loss: 0.5258
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4939 - val_accuracy: 0.7532 - val_loss: 0.5267
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.4859 - val_accuracy: 0.7403 - val_loss: 0.5270
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5041 - val_accuracy: 0.7597 - val_loss: 0.5266
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.4898 - val_accuracy: 0.7532 - val_loss: 0.5288
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.4948 - val_accuracy: 0.7532 - val_loss: 0.5273
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4956 - val_accuracy: 0.7468 - val_loss: 0.5271
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4930 - val_accuracy: 0.7597 - val_loss: 0.5277
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.4878 - val_accuracy: 0.7597 - val_loss: 0.5277
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5016 - val_accuracy: 0.7597 - val_loss: 0.5281
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4801 - val_accuracy: 0.7597 - val_loss: 0.5282
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4885 - val_accuracy: 0.7662 - val_loss: 0.5282
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7687 - loss: 0.4744 - val_accuracy: 0.7597 - val_loss: 0.5278
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7557 - loss: 0.4724 - val_accuracy: 0.7662 - val_loss: 0.5286
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7492 - loss: 0.4793 - val_accuracy: 0.7532 - val_loss: 0.5279
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4963 - val_accuracy: 0.7662 - val_loss: 0.5266
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4724 - val_accuracy: 0.7532 - val_loss: 0.5257
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.5072 - val_accuracy: 0.7597 - val_loss: 0.5258
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7508 - loss: 0.4892 - val_accuracy: 0.7532 - val_loss: 0.5257
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7508 - loss: 0.4894 - val_accuracy: 0.7792 - val_loss: 0.5260
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7476 - loss: 0.4903 - val_accuracy: 0.7662 - val_loss: 0.5250
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7508 - loss: 0.5038 - val_accuracy: 0.7532 - val_loss: 0.5259
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7492 - loss: 0.4835 - val_accuracy: 0.7532 - val_loss: 0.5254
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 0.4823 - val_accuracy: 0.7532 - val_loss: 0.5253
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4544 - val_accuracy: 0.7532 - val_loss: 0.5241
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4824 - val_accuracy: 0.7597 - val_loss: 0.5241
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4893 - val_accuracy: 0.7532 - val_loss: 0.5251
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4891 - val_accuracy: 0.7662 - val_loss: 0.5251
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4608 - val_accuracy: 0.7727 - val_loss: 0.5243
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4713 - val_accuracy: 0.7662 - val_loss: 0.5258
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4674 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4618 - val_accuracy: 0.7532 - val_loss: 0.5301
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4835 - val_accuracy: 0.7532 - val_loss: 0.5297
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4710 - val_accuracy: 0.7468 - val_loss: 0.5299
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4910 - val_accuracy: 0.7532 - val_loss: 0.5289
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4708 - val_accuracy: 0.7532 - val_loss: 0.5294
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4778 - val_accuracy: 0.7532 - val_loss: 0.5290
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4755 - val_accuracy: 0.7532 - val_loss: 0.5308
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4798 - val_accuracy: 0.7532 - val_loss: 0.5314
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4676 - val_accuracy: 0.7403 - val_loss: 0.5324
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4816 - val_accuracy: 0.7662 - val_loss: 0.5308
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4839 - val_accuracy: 0.7468 - val_loss: 0.5314
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4614 - val_accuracy: 0.7468 - val_loss: 0.5304
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4628 - val_accuracy: 0.7468 - val_loss: 0.5310
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4777 - val_accuracy: 0.7468 - val_loss: 0.5313
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4828 - val_accuracy: 0.7468 - val_loss: 0.5313
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4699 - val_accuracy: 0.7468 - val_loss: 0.5311
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4701 - val_accuracy: 0.7532 - val_loss: 0.5300
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4907 - val_accuracy: 0.7662 - val_loss: 0.5299
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4868 - val_accuracy: 0.7662 - val_loss: 0.5303
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4623 - val_accuracy: 0.7532 - val_loss: 0.5309
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4726 - val_accuracy: 0.7532 - val_loss: 0.5303
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4773 - val_accuracy: 0.7662 - val_loss: 0.5304
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4900 - val_accuracy: 0.7597 - val_loss: 0.5304
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4661 - val_accuracy: 0.7662 - val_loss: 0.5296
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4565 - val_accuracy: 0.7662 - val_loss: 0.5278
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4895 - val_accuracy: 0.7597 - val_loss: 0.5266
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5013 - val_accuracy: 0.7727 - val_loss: 0.5248
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4654 - val_accuracy: 0.7597 - val_loss: 0.5256
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.4796 - val_accuracy: 0.7662 - val_loss: 0.5260
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4804 - val_accuracy: 0.7597 - val_loss: 0.5269
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4596 - val_accuracy: 0.7662 - val_loss: 0.5266
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4592 - val_accuracy: 0.7597 - val_loss: 0.5270
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5029 - val_accuracy: 0.7532 - val_loss: 0.5275
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4626 - val_accuracy: 0.7532 - val_loss: 0.5266
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4794 - val_accuracy: 0.7532 - val_loss: 0.5279
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.4773 - val_accuracy: 0.7532 - val_loss: 0.5271
Epoch 162/200